- name: create insight dir
  file: path='{{ mn_insight_path }}' state=directory recurse=true

- name: copy insight docker compose
  template:
    src: '{{ item }}.j2'
    dest: '{{ mn_insight_path }}/{{ item }}'
  loop:
    - docker-compose.yml
    - dashcore-node.json
    - .env

- name: start insight
  docker_service:
    project_src: '{{ mn_insight_path }}'
    state: present
    restarted: yes
    pull: yes

- name: check Insight container
  assert:
    that: 'insight.insight.state.running'
