---

- name: get tenderdash container id
  command: docker ps -aqf "name=mn_evo_services_tendermint"
  register: tenderdash_container_id

- name: set up filebeat log monitoring
  include_role:
    name: elastic.beats
  vars:
    beats_version: "{{ elastic_version }}"
    beat: filebeat
    beat_conf:
      setup:
        template:
          enabled: false
      filebeat:
        inputs:
          - type: log
            enabled: true
            json.message_key: msg
            json.keys_under_root: false
            exclude_files: ['\.gz$']
            index: "logs-drive.abci-{{ dash_network_name }}-%{[agent.version]}"
            paths:
              - "{{ mn_evo_services_path }}/logs/drive-json*.log*"
            processors:
              - timestamp:
                  field: json.time
                  layouts:
                    - UNIX_MS
              - if:
                  equals:
                    json.level: 10
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: trace
              - if:
                  equals:
                    json.level: 20
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: debug
              - if:
                  equals:
                    json.level: 30
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: info
              - if:
                  equals:
                    json.level: 40
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: warn
              - if:
                  equals:
                    json.level: 50
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: error
              - if:
                  equals:
                    json.level: 60
                then:
                  - add_fields:
                      target: log
                      fields:
                        level: fatal
              - add_fields:
                  target: event
                  fields:
                    dataset: "drive.abci-{{ dash_network_name }}"
              - rename:
                  fields:
                    - from: "json.msg"
                      to: "message"
                  ignore_missing: true
                  fail_on_error: true
              - drop_fields:
                  fields:
                    - json.pid
                    - json.hostname
                    - json.time
                  ignore_missing: true
          - type: container
            enabled: true
            json.message_key: _msg
            json.keys_under_root: false
            index: "logs-drive.tenderdash-{{ dash_network_name }}-%{[agent.version]}"
            paths:
              - '/var/lib/docker/containers/{{ tenderdash_container_id.stdout }}*/*.log'
            processors:
              - add_fields:
                  target: event
                  fields:
                    dataset: "drive.tenderdash-{{ dash_network_name }}"
              - rename:
                  fields:
                    - from: "json._msg"
                      to: "message"
                  ignore_missing: true
                  fail_on_error: true
              - rename:
                  fields:
                    - from: "json.level"
                    - to: "log.level"
    output_conf:
      elasticsearch:
        hosts:
          - "{{ hostvars['logs-1'].private_ip }}:9200"
        username: "{{ elastic_username }}"
        password: "{{ elastic_password }}"
    logging_conf:
      level: info
      files:
        rotateeverybytes: 10485760
