---

- name: Set swap_file variable
  ansible.builtin.set_fact:
    swap_file: /swapfile

- name: Check if swap file exists
  ansible.builtin.stat:
    path: "{{ swap_file }}"
  register: swap_file_check

- name: Create swap file
  ansible.builtin.command: fallocate -l {{ swap_space }} {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Set permissions on swap file
  ansible.builtin.file:
    path: "{{ swap_file }}"
    mode: 0600

- name: Format swap file
  ansible.builtin.command: mkswap {{ swap_file }}
  when: not swap_file_check.stat.exists

- name: Add to fstab
  ansible.builtin.lineinfile:
    dest: /etc/fstab
    regexp: "{{ swap_file }}"
    line: "{{ swap_file }} none swap sw 0 0"

- name: Turn on swap
  ansible.builtin.command: swapon -av
  register: result
  changed_when: '"already active" not in result.stdout'

- name: Set swappiness
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "10"
  notify: Reset swap
