---

# Requires "masternode_names" variable

- name: import masternode owner private key
  command: 'dash-cli {{ masternode_wallet_rpc_args }} importprivkey {{ masternodes[item].owner.private_key }} "" false'
  with_items: '{{ masternode_names }}'

- name: rescan blockchain
  command: 'dash-cli {{ masternode_wallet_rpc_args }} rescanblockchain'

# fund
# TODO: this should run on the condition that the faucet does not already have enough balance
- name: fund 1 coin for ProTx
  include_tasks: ./roles/mn-fund-collateral/tasks/fund_collateral.yml
  vars:
    amount: 1

- name: generate at least one block to confirm funding transactions
  include_role:
    name: generate-blocks
  vars:
    num_blocks: 1
    balance_needed: 0

- include_tasks: createprovidertx.yml
  vars:
    masternode: "{{ masternodes[item] }}"
    masternode_name: "{{ item }}"
  with_items: '{{ masternode_names }}'


- name: generate at least one block to confirm protxs
  include_role:
    name: generate-blocks
  vars:
    num_blocks: 1
    balance_needed: 0

# verify

- name: get list of ProTx transactions from the wallet
  command: dash-cli protx list wallet true
  register: get_protx_list_result

- set_fact:
    registered_masternode_names: []

- name: get names of registered masternodes
  set_fact:
    registered_masternode_names: "{{ registered_masternode_names|default([]) + [ item ] }}"
  when: get_protx_list_result.stdout|from_json|json_query("[?state.ownerAddress=='" + masternodes[item].owner.address + "']")
  with_items: '{{ masternode_names }}'

- fail:
    msg: ProTX transactions were not created
  when: masternode_names | difference(registered_masternode_names)
