---

- name: generate fixed amount of blocks
  shell: dash-cli {{ faucet_rpc_args }} generatetoaddress {{ num_blocks }} {{ miner_payment_address }} > /dev/null
  when: num_blocks|int > 0

# TODO avoid first call if not needed
- name: generate enough blocks to have {{ balance_needed|default(0) }} coins
  shell: dash-cli {{ faucet_rpc_args }} generatetoaddress 10 {{ miner_payment_address }} > /dev/null && dash-cli {{ faucet_rpc_args }} getbalance
  when: balance_needed|float > 0
  register: balance_result
  until: balance_result.stdout|float >= balance_needed|float
  retries: 200
  delay: 0

- set_fact:
    new_balance: "{{ balance_result.stdout|float }}"
  when: balance_needed|float > 0
