---

# Requires "masternodes" and "masternode_names" variables

- name: get list of banned masternode protx
  include: mn-find-protx.yml
  vars:
    masternode: "{{ masternodes[item] }}"
    masternode_name: "{{ item }}"
  with_items: '{{ masternode_names }}'

# unban

- name: create ProUpServTx for banned masternodes
  include: createproupservtx.yml
  vars:
    masternode: "{{ masternodes[item] }}"
    masternode_name: "{{ item }}"
  with_items: '{{ masternode_names }}'

- name: generate at least one block to confirm protxs
  include_role:
    name: generate-blocks
  vars:
    num_blocks: 1
    balance_needed: 0

# verify

- name: get list of ProTx transactions from the wallet
  command: dash-cli protx list wallet true
  register: get_protx_list_result

- set_fact:
    registered_masternode_names: []

- name: get names of registered masternodes
  set_fact:
    registered_masternode_names: "{{ registered_masternode_names|default([]) + [ item ] }}"
  when: get_protx_list_result.stdout|from_json|json_query("[?state.ownerAddress=='" + masternodes[item].owner.address + "']")
  with_items: '{{ masternode_names }}'

- fail:
    msg: ProTX transactions were not created
  when: masternode_names | difference(registered_masternode_names)
