---

- name: Disable apparmor for tcpdump
  ansible.builtin.command: apparmor_parser -R /etc/apparmor.d/usr.sbin.tcpdump
  register: result
  failed_when: result.rc !=0 or result.rc != 2
  changed_when: result.rc == 0

- name: Configure tcpdump
  ansible.builtin.template:
    src: 'tcpdump.service'
    dest: '/etc/systemd/system/tcpdumpd.service'
    mode: 0644

- name: Make sure tcpdump unit is running
  ansible.builtin.systemd:
    state: restarted
    name: tcpdumpd
    daemon_reload: true

- name: Copy logrotate script
  ansible.builtin.template:
    src: 'tcpdumpd'
    dest: '/etc/logrotate.d/tcpdumpd'
    mode: 0644
