---

- name: Ensure /etc/docker exists
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: 0700
    owner: root
    group: root

- name: Create daemon.json
  ansible.builtin.template:
    src: 'daemon.json.j2'
    dest: '/etc/docker/daemon.json'
    owner: root
    group: root
    mode: 0640
  notify: Restart docker

- name: Update systemd service
  become: true
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: '/lib/systemd/system/{{ item }}'
    mode: 0644
  loop:
    - 'docker.service'
    - 'docker.socket'
  notify: Restart docker

- name: Update upstart defaults
  become: true
  ansible.builtin.copy:
    src: docker
    dest: /etc/default/
    mode: 0644
